# Generated by Django 5.2.7 on 2025-11-06 17:43

import django.core.validators
import django_mongodb_backend.fields
import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='شماره تماس باید با 09 شروع شود و 11 رقم باشد', regex='^09\\d{9}$')])),
                ('post_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='کد پستی باید ۱۰ رقم باشد', regex='^\\d{10}$')])),
                ('birthday', models.DateField(blank=True, null=True)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('image_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('image_size', models.IntegerField(blank=True, null=True)),
                ('image_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive'), ('banned', 'banned')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'indexes': [models.Index(fields=['phone'], name='marketplace_phone_f28ae4_idx'), models.Index(fields=['email'], name='marketplace_email_3d26a6_idx'), models.Index(fields=['status'], name='marketplace_status_c25311_idx')],
            },
            managers=[
                ('objects', marketplace.models.UserManager()),
            ],
        ),
    ]
